# Generated by Django 5.0.3 on 2024-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
