# Generated by Django 5.0.3 on 2024-05-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_otpverification_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='max_otp_try',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
