# Generated by Django 5.0.3 on 2024-05-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_otpverification_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='max_otp_try',
        ),
    ]
