# Generated by Django 5.0.3 on 2024-05-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_otpverification_max_otp_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='max_otp_try',
            field=models.IntegerField(default=0),
        ),
    ]
