# Generated by Django 5.0.3 on 2024-05-09 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_otpverification_max_otp_try'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='max_otp_try',
        ),
    ]
