# Generated by Django 5.0.3 on 2024-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_otpverification_max_otp_try'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='email',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='max_try',
            field=models.IntegerField(default=0),
        ),
    ]
