# Generated by Django 5.0.3 on 2024-06-15 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_securityquestion_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_security', to=settings.AUTH_USER_MODEL),
        ),
    ]
